name: task18
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  color: ^3.0.0
  compute: ^1.0.2
  equatable: ^2.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
